apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prod-bring-recyling
  namespace: prod-bring-recycling
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-certs
spec:
  tls:
    - hosts:
        - bringrecycling.mvpstudio.org
      secretName: prod-bring-recyling-cert
  rules:
    - host: bringrecycling.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: bring-recycling-react
              servicePort: 80
    - host: bringrecycling.mvpstudio.org
      http:
        paths:
          - path: /api
            backend:
              serviceName: bring-recycling-webserver
              servicePort: 5000
