apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ecan-soar-prod
  namespace: prod-ecan-soar
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-certs
spec:
  tls:
    - hosts:
        - soar.prod.apps.mvpstudio.org
      secretName: ecan-soar-prod-cert
  rules:
    - host: soar.prod.apps.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: ecan-soar-web
              servicePort: 80
