apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: emerald-citizen-stage
  namespace: stage-emerald-citizen
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-certs
spec:
  tls:
    - hosts:
        - test.emeraldcitizen.org
      secretName: emerald-citizen-stage-cert
  rules:
    - host: test.emeraldcitizen.org
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 80
