apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: eug-cal-stage
  namespace: eug-cal-stage
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-certs
spec:
  tls:
    - hosts:
        - eugcal.stage.apps.mvpstudio.org
      secretName: eug-cal-stage-cert
  rules:
    - host: eugcal.stage.apps.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: eug-cal-web
              servicePort: 80
