apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: eug-cal-prod
  namespace: eug-cal-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-certs
spec:
  tls:
    - hosts:
        - eugcal.prod.apps.mvpstudio.org
        - eugcal.com
        - www.eugcal.com
      secretName: eug-cal-prod-cert
  rules:
    - host: eugcal.prod.apps.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: eug-cal-web
              servicePort: 80
    - host: eugcal.com
      http:
        paths:
          - path: /
            backend:
              serviceName: eug-cal-web
              servicePort: 80
    - host: www.eugcal.com
      http:
        paths:
          - path: /
            backend:
              serviceName: eug-cal-web
              servicePort: 80
