apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: eugene-food-scene-stage
  namespace: eugene-food-scene-stage
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-certs
spec:
  tls:
    - hosts:
        - eugenefoodscene.stage.apps.mvpstudio.org
      secretName: eugene-food-scene-stage-cert
  rules:
    - host: eugenefoodscene.stage.apps.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: eugene-food-scene-web
              servicePort: 80
