apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: eugene-food-scene-prod
  namespace: eugene-food-scene-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-certs
spec:
  tls:
    - hosts:
        - eugenefoodscene.prod.apps.mvpstudio.org
        - eugenefoodscene.com
        - www.eugenefoodscene.com
      secretName: eugene-food-scene-prod-cert
  rules:
    - host: eugenefoodscene.prod.apps.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: eugene-food-scene-web
              servicePort: 80
    - host: eugenefoodscene.com
      http:
        paths:
          - path: /
            backend:
              serviceName: eugene-food-scene-web
              servicePort: 80
    - host: www.eugenefoodscene.com
      http:
        paths:
          - path: /
            backend:
              serviceName: eugene-food-scene-web
              servicePort: 80
