apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world
  namespace: hello-world
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-certs
spec:
  tls:
    - hosts:
        - helloworld.prod.apps.mvpstudio.org
        - helloworld.mvpstudio.org
      secretName: hello-world-cert
  rules:
    - host: helloworld.prod.apps.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 80
    - host: helloworld.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 80
