apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: little-help-book-prod
  namespace: little-help-book-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-certs
spec:
  tls:
    - hosts:
        - littlehelpbook.prod.apps.mvpstudio.org
        - www.littlehelpbook.com
        - littlehelpbook.com
      secretName: little-help-book-prod-cert
  rules:
    - host: littlehelpbook.prod.apps.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: little-help-book-web
              servicePort: 80
    - host: www.littlehelpbook.com
      http:
        paths:
          - path: /
            backend:
              serviceName: little-help-book-web
              servicePort: 80
    - host: littlehelpbook.com
      http:
        paths:
          - path: /
            backend:
              serviceName: little-help-book-web
              servicePort: 80
