apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: little-help-book-stage
  namespace: little-help-book-stage
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-certs
spec:
  tls:
    - hosts:
        - littlehelpbook.stage.apps.mvpstudio.org
        - lhb-exporter.stage.apps.mvpstudio.org
      secretName: little-help-book-stage-cert
  rules:
    - host: littlehelpbook.stage.apps.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: little-help-book-web
              servicePort: 80
    - host: lhb-exporter.stage.apps.mvpstudio.org
      http:
        paths:
          - path: /
            backend:
              serviceName: exporter
              servicePort: 80
