---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: hello-world-mapping
  namespace: ambassador-edge
spec:
  host: helloworld.mvpstudio.org
  prefix: /
  service: web.hello-world
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: hello-world-host
  namespace: ambassador-edge
spec:
  hostname: helloworld.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon+hello@gmail.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: hello-world-prod-mapping
  namespace: ambassador-edge
spec:
  host: helloworld.prod.apps.mvpstudio.org
  prefix: /
  service: web.hello-world
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: hello-world-prod-host
  namespace: ambassador-edge
spec:
  hostname: helloworld.prod.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon+helloprod@gmail.com
