apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: codechops-mapping
  namespace: ambassador-edge
spec:
  host: codechops.mvpstudio.org
  prefix: /
  service: codechops-wp.codechops
  # Set all the timeouts to 0 'cause when you do things like upgrade plugins in Wordpress
  # the HTTP requests that give you the status of the upgrade just wait until the upgrade
  # is complete which can be very slow. However, contrary to what the docs say
  # (https://www.getambassador.io/docs/latest/topics/using/timeouts/) a timeout
  # of 0 doesn't disable the timeout; it causes all the ambassador pods to die with errors like:
  #
  # ```
  # Proto constraint validation failed
  # (BootstrapValidationError.StaticResources: ["embedded message failed
  # validation"] | caused by StaticResourcesValidationError.Clusters[i]:
  # ["embedded message failed validation"] | caused by
  # ClusterValidationError.ConnectTimeout: ["value must be greater than "
  # "0s"])
  # ```
  #
  # so we just set it really high
  timeout_ms: 120000
  idle_timeout_ms: 120000
  connect_timeout_ms: 120000
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: codechops-host
  namespace: ambassador-edge
spec:
  hostname: codechops.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon+codechopsprod@gmail.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: codechops-dns-www-mapping
  namespace: ambassador-edge
spec:
  host: www.codechops.com
  prefix: /
  service: codechops-wp.codechops
  # See comments above
  timeout_ms: 120000
  idle_timeout_ms: 120000
  connect_timeout_ms: 120000
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: codechops-dns-www-host
  namespace: ambassador-edge
spec:
  hostname: www.codechops.com
  acmeProvider:
    email: mvpstudiooregon+codechopsprodwww@gmail.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: codechops-dns-mapping
  namespace: ambassador-edge
spec:
  host: codechops.com
  prefix: /
  service: codechops-wp.codechops
  # See comments above
  timeout_ms: 120000
  idle_timeout_ms: 120000
  connect_timeout_ms: 120000
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: codechops-dns-host
  namespace: ambassador-edge
spec:
  hostname: codechops.com
  acmeProvider:
    email: mvpstudiooregon+codechopsprodhost@gmail.com
