apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: codechops-mapping
  namespace: ambassador-edge
spec:
  host: codechops.mvpstudio.org
  prefix: /
  service: codechops-wp.codechops
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: codechops-host
  namespace: ambassador-edge
spec:
  hostname: codechops.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon+codechopsprod@gmail.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: codechops-dns-www-mapping
  namespace: ambassador-edge
spec:
  host: www.codechops.com
  prefix: /
  service: codechops-wp.codechops
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: codechops-dns-www-host
  namespace: ambassador-edge
spec:
  hostname: www.codechops.com
  acmeProvider:
    email: mvpstudiooregon+codechopsprodwww@gmail.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: codechops-dns-mapping
  namespace: ambassador-edge
spec:
  host: codechops.com
  prefix: /
  service: codechops-wp.codechops
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: codechops-dns-host
  namespace: ambassador-edge
spec:
  hostname: codechops.com
  acmeProvider:
    email: mvpstudiooregon+codechopsprodhost@gmail.com
