---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: openeugene-prod-mvp-mapping
  namespace: ambassador-edge
spec:
  host: openeugene.prod.apps.mvpstudio.org
  prefix: /
  service: openeugene-marketing-web.openeugene-marketing-prod
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: openeugene-prod-mvp-host
  namespace: ambassador-edge
spec:
  hostname: openeugene.prod.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: openeugene-prod-mapping
  namespace: ambassador-edge
spec:
  host: openeugene.org
  prefix: /
  # service: openeugene-marketing-web.openeugene-marketing-prod
  # The following two lines are a temporary redirect to a notion doc instead of the web page.
  # Remove them and replace with the line commented out line above when reverting.
  service: www.notion.so/Open-Eugene-f30160bbc8814fbdb4ff7285c751d001
  host_redirect: true
---
# Redirect www to non-www
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: openeugene-prod-www-mapping
  namespace: ambassador-edge
spec:
  host: www.openeugene.org
  prefix: /
  service: openeugene.org
  host_redirect: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: openeugene-prod-host
  namespace: ambassador-edge
spec:
  hostname: openeugene.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: openeugene-prod-www-host
  namespace: ambassador-edge
spec:
  hostname: www.openeugene.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
