---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: openeugene-stage-mvp-mapping
  namespace: ambassador-edge
spec:
  host: openeugene.stage.apps.mvpstudio.org
  prefix: /
  service: openeugene-marketing-web.openeugene-marketing-stage
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: openeugene-stage-mvp-host
  namespace: ambassador-edge
spec:
  hostname: openeugene.stage.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon+openeugstage@gmail.com
