---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: ambassador-certs
  namespace: default
spec:
  acme:
    email: "mvpstudiooregon@gmail.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-issuer-account-key
    solvers:
      - dns01:
          clouddns:
            project: mvpstudio
            serviceAccountSecretRef:
              name: cert-manager-service-account
              key: service-account.json
