---
# This is our main load balancer. It's set up to just send all traffic to Ambassador, our ingress controller, for
# routing.
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  # This ip was specifically reserved in GCP for the main mvp studio k8 cluster
  # If this resource gets deleted and re-created this should ensure it comes back with the same static ip
  loadBalancerIP: 35.233.220.107
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    service: ambassador
