---
# This is our main load balancer. It's set up to just send all traffic to Ambassador, our ingress controller, for
# routing.
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 35.233.220.107
  ports:
   - port: 80
  selector:
    service: ambassador
