---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: emerald-citizen-prod-mapping
  namespace: ambassador-edge
spec:
  host: emeraldcitizen.org
  prefix: /
  service: web.prod-emerald-citizen
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: emerald-citizen-prod-host
  namespace: ambassador-edge
spec:
  hostname: emeraldcitizen.org
  acmeProvider:
    email: mvpstudiooregon+emerald@gmail.com
