---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: emerald-citizen-stage-mapping
  namespace: ambassador-edge
spec:
  host: test.emeraldcitizen.org
  prefix: /
  service: web.stage-emerald-citizen
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: emerald-citizen-stage-host
  namespace: ambassador-edge
spec:
  hostname: test.emeraldcitizen.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
