apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-certs
  namespace: cert-manager
spec:
  acme:
    email: "mvpstudiooregon@gmail.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx
