---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-example
  labels:
    app: ceph-example
  namespace: ceph-example
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

