---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: ecan-soar-prod-mapping
  namespace: ambassador-edge
spec:
  host: soar.prod.apps.mvpstudio.org
  prefix: /
  service: ecan-soar-web.prod-ecan-soar
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: ecan-soar-prod-host
  namespace: ambassador-edge
spec:
  hostname: soar.prod.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
