---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: eugene-food-scene-prod-mapping
  namespace: ambassador-edge
spec:
  host: eugenefoodscene.prod.apps.mvpstudio.org
  prefix: /
  service: eugene-food-scene-web.eugene-food-scene-prod
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: eugene-food-scene-prod-host
  namespace: ambassador-edge
spec:
  hostname: eugenefoodscene.prod.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: eugene-food-scene-bare-dns-mapping
  namespace: ambassador-edge
spec:
  host: eugenefoodscene.com
  prefix: /
  service: eugene-food-scene-web.eugene-food-scene-prod
---
# Redirect www to non-www
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: eugene-food-scene-www-dns-mapping
  namespace: ambassador-edge
spec:
  host: www.eugenefoodscene.org
  prefix: /
  service: eugenefoodscene.org
  host_redirect: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: eugene-food-scene-dns-host
  namespace: ambassador-edge
spec:
  hostname: eugenefoodscene.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
