---
- hosts: minions
  vars:
     - ansible_become_password: "{{ sudo_pass }}"
  vars_files:
     - vault.yml
  tasks:
     - name: Install packages
       apt:
          name:
             - open-iscsi
             # Undocumented but per https://github.com/rook/rook/issues/2591 this appears
             # to be necessary.
             - lvm2
          state: present
       become: yes
     - name: Make iSCSI connections
       open_iscsi:
          discover: yes
          portal: 172.19.250.245
          auto_node_startup: yes
          login: yes
          node_auth: CHAP
          node_user: MVP_CHAP
          node_pass: "{{ iscsi_pass }}"
          target: "{{ iscsi_target }}"
       become: yes
