---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: eug-cal-prod-mapping
  namespace: ambassador-edge
spec:
  host: eugcal.prod.apps.mvpstudio.org
  prefix: /
  service: eug-cal-web.eug-cal-prod
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: eug-cal-prod-host
  namespace: ambassador-edge
spec:
  hostname: eugcal.prod.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: eug-cal-bare-dns-mapping
  namespace: ambassador-edge
spec:
  host: eugcal.com
  prefix: /
  service: eug-cal-web.eug-cal-prod
  use_websocket: true
---
# Redirect www to non-www
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: eug-cal-www-dns-mapping
  namespace: ambassador-edge
spec:
  host: www.eugcal.com
  prefix: /
  service: eugcal.com
  host_redirect: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: eug-cal-dns-host
  namespace: ambassador-edge
spec:
  hostname: eugcal.com
  acmeProvider:
    email: mvpstudiooregon@gmail.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: eug-cal-dns-www-host
  namespace: ambassador-edge
spec:
  hostname: www.eugcal.com
  acmeProvider:
    email: mvpstudiooregon@gmail.com
