---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: eug-cal-stage-mapping
  namespace: ambassador-edge
spec:
  host: eugcal.stage.apps.mvpstudio.org
  prefix: /
  service: eug-cal-web.eug-cal-stage
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: eug-cal-stage-host
  namespace: ambassador-edge
spec:
  hostname: eugcal.stage.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
