---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: card-night-fever-prod-mapping
  namespace: ambassador-edge
spec:
  host: cardnightfever.prod.apps.mvpstudio.org
  prefix: /
  service: card-night-fever-web.card-night-fever-prod
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: card-night-fever-prod-host
  namespace: ambassador-edge
spec:
  hostname: cardnightfever.prod.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: card-night-fever-bare-dns-mapping
  namespace: ambassador-edge
spec:
  host: cardnightfever.com
  prefix: /
  service: card-night-fever-web.card-night-fever-prod
  use_websocket: true
---
# Redirect www to non-www
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: card-night-fever-www-dns-mapping
  namespace: ambassador-edge
spec:
  host: www.cardnightfever.com
  prefix: /
  service: cardnightfever.com
  host_redirect: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: card-night-fever-dns-host
  namespace: ambassador-edge
spec:
  hostname: cardnightfever.com
  acmeProvider:
    email: mvpstudiooregon@gmail.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: card-night-fever-dns-www-host
  namespace: ambassador-edge
spec:
  hostname: www.cardnightfever.com
  acmeProvider:
    email: mvpstudiooregon@gmail.com
