---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: card-night-fever-stage-mapping
  namespace: ambassador-edge
spec:
  host: cardnightfever.stage.apps.mvpstudio.org
  prefix: /
  service: card-night-fever-web.card-night-fever-stage
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: card-night-fever-stage-host
  namespace: ambassador-edge
spec:
  hostname: cardnightfever.stage.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
