---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: little-help-book-prod-mapping
  namespace: ambassador-edge
spec:
  host: littlehelpbook.prod.apps.mvpstudio.org
  prefix: /
  service: little-help-book-web.little-help-book-prod
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: little-help-book-prod-host
  namespace: ambassador-edge
spec:
  hostname: littlehelpbook.prod.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
