---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: little-help-book-prod-mapping
  namespace: ambassador-edge
spec:
  host: littlehelpbook.prod.apps.mvpstudio.org
  prefix: /
  service: little-help-book-web.little-help-book-prod
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: little-help-book-prod-com-mapping
  namespace: ambassador-edge
spec:
  host: littlehelpbook.com
  prefix: /
  service: little-help-book-web.little-help-book-prod
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: little-help-book-prod-www-com-mapping
  namespace: ambassador-edge
spec:
  host: www.littlehelpbook.com
  prefix: /
  service: little-help-book-web.little-help-book-prod
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: little-help-book-prod-com-host
  namespace: ambassador-edge
spec:
  hostname: littlehelpbook.com
  acmeProvider:
    email: mvpstudiooregon+helpbook@gmail.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: little-help-book-prod-host
  namespace: ambassador-edge
spec:
  hostname: littlehelpbook.prod.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon+helpbookmvp@gmail.com
