---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: little-help-book-exporter-stage-mapping
  namespace: ambassador-edge
spec:
  host: lhb-exporter.stage.apps.mvpstudio.org
  prefix: /
  service: exporter.little-help-book-stage
  timeout_ms: 120000
  idle_timeout_ms: 120000
  connect_timeout_ms: 120000
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: little-help-book-exporter-stage-host
  namespace: ambassador-edge
spec:
  hostname: lhb-exporter.stage.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon+lhb-exporter@gmail.com
