---
# Continnu has an HA Proxy instance for our public ip address that sends http traffic to port 30036 and https traffic to 30037 load balanced to all nodes.
# This routes that traffic to our ambassador deployment.
apiVersion: v1
kind: Service
metadata:
  name: ambassador-public
  namespace: ambassador-edge
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30036
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      nodePort: 30037
      protocol: TCP
  selector:
    service: ambassador
