apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: fire-refuge-mapping
  namespace: ambassador-edge
spec:
  host: firerefuge.mvpstudio.org
  prefix: /
  service: fire-refuge-prod.fire-refuge-web
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: fire-refuge-host
  namespace: ambassador-edge
spec:
  hostname: firerefuge.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
---
